### ISSUE TITLE
Add the ability to define shared views

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/OpenColorIO#1030]
When authoring configs with a large number of displays, the display/view section of the config can become quite lengthy and difficult to read.  In other words, with D displays, V views, there would be V x D definitions (assuming each view is used with each display, which is a common scenario).  Some configs will also define copies of the same view with and without looks, leading to even more definitions.  Reading and maintaining such a config may become difficult and error-prone.  

This proposal is to allow a config to use the notion of a "shared view" which is a view that is defined once but may be used with multiple displays.

To illustrate with an overly simple example from the Imageworks spi-vfx config, it would allow replacing this:

```
displays:
  DCIP3:
    - !<View> {name: Film, colorspace: p3dci8}
    - !<View> {name: Log, colorspace: lg10}
    - !<View> {name: Raw, colorspace: nc10}
  sRGB:
    - !<View> {name: Film, colorspace: srgb8}
    - !<View> {name: Log, colorspace: lg10}
    - !<View> {name: Raw, colorspace: nc10}

```
with this:

```
shared_views:
    - !<View> {name: Log, colorspace: lg10}
    - !<View> {name: Raw, colorspace: nc10}

displays:
  DCIP3:
    - !<View> {name: Film, colorspace: p3dci8}
    - !<Views> [ Log, Raw ]
  sRGB:
    - !<View> {name: Film, colorspace: srgb8}
    - !<Views> [ Log, Raw ]

```
Obviously with only two displays and three views there is not much benefit, but when the number of displays gets large there is a big benefit.

A previous PR added the notion of a display color space and a view transform.  This allows breaking down the conversion from a scene-linear color space into a view transform that converts scene-linear to display-linear colorimetry followed by a display color space.  An example of how that looks in config syntax is:

```
displays:
  sRGB:
    - !<View> {name: ACES, view_transform: ACES-sdr-video, display_colorspace: sRGB}
    - !<Views> [ Log, Raw ]
  Rec709:
    - !<View> {name: ACES, view_transform: ACES-sdr-video, display_colorspace: Rec709}
    - !<Views> [ Log, Raw ]

```
Such a config would also define display color spaces for sRGB and Rec709:

```
display_colorspaces:
    - !<ColorSpace> 
      name: sRGB
      from_display_reference: <omitted for brevity>
    - !<ColorSpace> 
      name: Rec709
      from_display_reference: <omitted for brevity>

```
With the new shared view feature, it would be possible to define a shared view and have the display_colorspace be filled in automatically by OCIO.  For example, the above becomes:

```
shared_views:
    - !<View> {name: ACES, view_transform: ACES-sdr-video, 
               display_colorspace: <USE_DISPLAY_NAME>}
    - !<View> {name: Log, colorspace: lg10}
    - !<View> {name: Raw, colorspace: nc10}

displays:
  sRGB:
    - !<Views> [ ACES, Log, Raw ]
  Rec709:
    - !<Views> [ ACES, Log, Raw ]

```
The requirement for any shared views that define a view_transform but do not have a specific display_transform is that each display they are used with has a corresponding display color space with the same name.  In other words, the name of the display in the "displays" section of the config needs to match the "name" of one of the color spaces in the "display_colorspaces" section. The special string token <USE_DISPLAY_NAME> is used as a placeholder in the config to make it easier for people to read and understand what is happening.

As with any other view, a shared view may appear (or not) in the list of active_views.
