### ISSUE TITLE
ColorSpace 'alias' mechanism

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1129]
*edit: See @doug-walker's proposal and discussion below
> [...] I'd like to propose an alternate solution which is to allow use of an "alias" key in a ColorSpace. This would allow the alternate name to be used anywhere the main name is used. This would include file rules but also command-line tools and other scenarios. Here is an example (the fourth line is the only difference from the current ACES config):
> 
> 
> ```
>   - !<ColorSpace>
>     name: ACES - ACEScct
>     family: ACES
>     alias: acescct
>     equalitygroup: ""
>     bitdepth: 32f
>     description: |
>       The ACEScct color space
>       
>       ACES Transform ID : ACEScsc.ACEScct_to_ACES
>     isdata: false
>     allocation: uniform
>     allocationvars: [-0.249136, 1.468]
>     to_reference: !<GroupTransform>
>       children:
>         - !<FileTransform> {src: ACEScct_to_linear.spi1d, interpolation: linear}
>         - !<MatrixTransform> {matrix: [0.695452, 0.140679, 0.163869, 0, 0.0447946, 0.859671, 0.0955343, 0, -0.00552588, 0.00402521, 1.0015, 0, 0, 0, 0, 1]}
> ```

Original post:
I would like to be able to repurpose the ColorSpace equalityGroup attribute to serve as ad-hoc colorspace 'aliases' where filename parsing is concerned. 

It's not uncommon for configs to contain copies of the same colorspace with alternate naming (and sometimes different families) --  E.g., "ACES - ACES2065-1", "aces", and "lin_ap0" are identical, and are found under different 'family paths'. 
Sometimes, a config will feature colorspaces with longer, human-friendly names prominently in interfaces and colorspace family hierarchy; and tucked away (or perhaps hidden in v2) are duplicate colorspaces with 'short names', often intended to serve as a filename 'color token', as is necessary for strict-parsing workflows. 

I propose either creating a new File Rule type for matching colorspace equalityGroups in a string, or updating the existing PathSearchRule to optionally search for equalityGroups as well. 

That's the primary proposal -- should be modest enough of a challenge for me to handle -- but it would be nice to reference colorspaces by their equality groups as shorthand for their actual names throughout OCIO; perhaps even have a place for them in menu interfaces, if wanted. 

Thoughts?

**Comment by sobotka** [comment]
+1 if there is a way to reduce the stanzas that define the actual transforms.

**Comment by doug-walker** [comment]
@zachlewis , thanks for raising this topic.  I've also had this on my list to bring up at a working group meeting because the use of aliases in the ACES config is less than ideal for a number of reasons:

1.  It requires duplicate ColorSpace definitions.  This bloats the config, is error-prone, and difficult to maintain.  For example, the equalitygroup is set on many of the aliases to point to the original but a lot of them do not, why?  Also, for those that do use the equalitygroup, there is no check to see if the redefined transforms actually do the same as the original.  This could be a difficult bug to track down, if there were an error.

2.  It adds a huge number of "duplicate" color spaces to application menus.  The new inactive_colorspaces feature could be used to remove these, but that was primarily intended to handle deprecated or internal colorspace definitions.  If the list grows to a hundred spaces (as it could with ACES), I think another mechanism would be helpful.  Also, one could make the case that a user would like to have the duplicates shown in menus in some cases, so that is another reason for wanting another mechanism than inactive_colorspaces.

3.  As you point out, the file rules would be nicer if you could set the color space for the rule using the friendly longer name but also have it pick up the shorter name automatically, without requiring duplicate rules.

Based on this, I'd like to propose an alternate solution which is to allow use of an "alias" key in a ColorSpace.  This would allow the alternate name to be used anywhere the main name is used.  This would include file rules but also command-line tools and other scenarios.  Here is an example (the fourth line is the only difference from the current ACES config):

```
  - !<ColorSpace>
    name: ACES - ACEScct
    family: ACES
    alias: acescct
    equalitygroup: ""
    bitdepth: 32f
    description: |
      The ACEScct color space
      
      ACES Transform ID : ACEScsc.ACEScct_to_ACES
    isdata: false
    allocation: uniform
    allocationvars: [-0.249136, 1.468]
    to_reference: !<GroupTransform>
      children:
        - !<FileTransform> {src: ACEScct_to_linear.spi1d, interpolation: linear}
        - !<MatrixTransform> {matrix: [0.695452, 0.140679, 0.163869, 0, 0.0447946, 0.859671, 0.0955343, 0, -0.00552588, 0.00402521, 1.0015, 0, 0, 0, 0, 1]}
```
