### ISSUE TITLE
LookTransform Inverse direction issue

### ISSUE THREAD

**Issue by remia** [AcademySoftwareFoundation/OpenColorIO#1178]
We stumbled upon a rather unusual config using the `LookTransform` inside a `GroupTransform`, it seems that the config breaks when the `LookTransform` is used in the inverse direction. A simplified version of the problematic config:
```
  - !<ColorSpace>
    name: vd_graded
    to_reference: !<GroupTransform>
      children:
        - !<LookTransform> {src: raw, dst: vd, looks: look1, direction: inverse}
```

The `LookTransform` is probably missing a `CombineTransformDirections` step that prevent it from working correctly in a situation like this. We were under an old OCIO version but the issue appears to be in master too.

Here is a quick path and dirty unit test to reproduce: https://gist.github.com/remia/2a928bc32bb1e9b514dff30f98782b2a

I wonder if there would be a way to perform this `CombineTransformDirections` at a higher level to avoid this kind of issue ?
