### ISSUE TITLE
Invoking NamedTransforms from within a config

### ISSUE THREAD

**Issue by zachlewis** [AcademySoftwareFoundation/OpenColorIO#1257]
Presented in three acts.

### Act I

If I recall, the means for invoking `NamedTransforms` from within a config is with a `ColorSpaceTransform` that provides _either_ a single `src` or `dst` attribute; e.g.:

```
<!ColorSpaceTransform> {src: my_named_transform}>
```

Looking back, I can't seem to find much more information, and of the NamedTransforms tests, most are concerned with creating ad-hoc `Processors` referencing `NamedTransforms` directly, as opposed to from within a config.

If I wanted to use a `NamedTransform` in the inverse direction in a config or a `GroupTransform`, would that look like:

  1. `<!ColorSpaceTransform> {src: my_named_transform, direction=inverse}`
  2. `<!ColorSpaceTransform> {dst: my_named_transform}`
  3. Either
  4. Neither

### Act II

If `ColorSpaceTransforms` used like such are indeed the correct mechanism for calling `NamedTransforms` in a config, the Python bindings for `ColorSpaceTransform` still need to be updated to reflect that usage:

```
from PyOpenColorIO import ColorSpaceTransform, BuiltinTransform, NamedTransform
named_transform = NamedTransform(
    name='my_named_transform',
    forwardTransform=BuiltinTransform('IDENTITY'),
)

xform = ColorSpaceTransform(src=named_transform.getName())
```
yikes:
```
PyOpenColorIO.Exception: ColorSpaceTransform: empty destination color space name.
```

### Act III

Proposal: Can we optionally invoke `NamedTransforms` with `FileTransforms`?
Specifically, I'd like to use `NamedTransforms` as a fail-over for `FileTransforms`.

Consider the following snippet:
```
ocio_profile_version: 2

search_path: luts/$SHOT
...

colorspaces:
  - !<ColorSpace>
    name: shot camera
    family: ""
    equalitygroup: ""
    bitdepth: unknown
    isdata: false
    encoding: log
    allocation: uniform
    from_scene_reference: !<FileTransform> {src: camera_log_to_scene_linear.ctf}
named_transforms:
  - !<NamedTransform>
    name: camera_log_to_scene_linear.ctf
    transform: !<BuiltinTransform> {style: ARRI_ALEXA-LOGC-EI800-AWG_to_ACES2065-1}
```

Note we have a `NamedTransform` whose name happens to match exactly what the `FileTransform` in the "shot camera" color space is looking for. Also note the $SHOT environment variable in the search path.

What'd I'd like is for the "shot camera" color space to behave by default like a hypothetical "LogC-AWG" would, EXCEPT in cases where the resolved context points to valid transforms on disk.

Said differently, I'd like to optionally override the default behavior of the "shot camera" color space as needed on a shot-by-shot basis by publishing bespoke color transform files to "luts/$SHOT/camera_log_to_scene_linear.ctf".

Similar pipelines are currently possible in OCIO v1, but they require that one always publishes file-based-transforms articulating the default behavior strategically into the search path (e.g., to a general show-wide location at the end of the search path); whereas the proposed feature permits one to define default behavior directly in the config itself. In other words, configs could ostensibly remain entirely self-contained, while also permitting one to override behavior with file-based-transforms as needed. 

(I can split the FileTransform proposal into its own ticket if it's worth considering separating out)
