### ISSUE TITLE
scene_linear sanity, and look-applying in OCIODisplay

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#139]
If role scene_linear isn't defined, the Nuke nodes segfault at

```
std::string defaultColorSpaceName = config->getColorSpace(OCIO::ROLE_SCENE_LINEAR)->getName();
```

Slightly confusingly (and maybe relatedly), ociocheck prints an error, but still passes the sanity check:

```
** ColorSpaces **
Error: scene_linear role must be defined.

[...]

Passed Sanity Check.
```

..which I noticed while playing with the new Look feature, and was narrowing down a problem. With the config:

```

---
ocio_profile_version: 1

roles:
  scene_linear: lnf

displays:
  sRGB:
    - !<View> {name: Film, colorspace: srgb8}
    - !<View> {name: FilmGraded, colorspace: srgb8, look: graded}

looks:
  - !<Look>
    name: grade
    process_space: lnf
    transform: !<ExponentTransform> {value: [2, 1, 1, 1]}

colorspaces:
  - !<ColorSpace>
    name: lnf
    family: ln
    bitdepth: 32f

  - !<ColorSpace>
    name: srgb8
    family: srgb
    from_reference: !<ExponentTransform> {value: [2.6, 2.6, 2.6, 1], direction: inverse}
```

When using the OCIODisplay node, it doesn't seem to apply the look transform - I'd expect the two branches to look identical:

```
set cut_paste_input [stack 0]
version 6.3 v1
CheckerBoard2 {
 inputs 0
 name CheckerBoard1
 selected true
 xpos -55
 ypos -238
}
set N2520d6e0 [stack 0]
OCIOLookTransform {
 name OCIOLookTransform1
 selected true
 xpos -109
 ypos -134
}
OCIODisplay {
 view FilmGraded
 name OCIODisplay1
 selected true
 xpos -109
 ypos -110
}
push $N2520d6e0
OCIODisplay {
 view FilmGraded
 name OCIODisplay2
 selected true
 xpos -11
 ypos -109
}
```
