### ISSUE TITLE
Strange Behavior of Grading Primary Transform's Contrast Pivot

### ISSUE THREAD

**Issue by EaryChow** [AcademySoftwareFoundation/OpenColorIO#1662]
What is the expected behavior for Grading Primary Transform's contrast pivot? 

I am trying to write some looks with process_space being a custom Log encoding, I want the contrast to have 0.18 middle grey as anchor point that doesn't move when the contrast change. Therefore I wrote something like:
```
  - !<Look>
    name: Extremely Low Contrast
    process_space: AgX Log
    description: A Very Very Low Contrast Look
    transform: !<GroupTransform>
        children:
          - !<GradingPrimaryTransform>
            style: log
            contrast: {rgb: [0.2, 0.2, 0.2], master: 1}
            pivot: {contrast: 0.18}
```

I have the style set to `log` since the process_space is a custom log space. I have pivot set to 0.18 hoping it will not move the 0.18 middle grey when changing contrast. 

As I have read here: https://opencolorio.readthedocs.io/en/latest/api/transforms.html
> Regardless of whether linear/video/log-style is being used, the pivot is always expressed in linear. In other words, a pivot of 0.18 is always mid-gray.

But when I actually load the config up and use it:
![image](https://user-images.githubusercontent.com/59176246/176982733-48642066-58ae-4db5-ac1e-e969791492d0.png)

If you change the pivot to 0.2121:
```
    transform: !<GroupTransform>
        children:
          - !<GradingPrimaryTransform>
            style: log
            contrast: {rgb: [0.2, 0.2, 0.2], master: 1}
            pivot: {contrast: 0.2121}
```

And now:
![image](https://user-images.githubusercontent.com/59176246/176982773-ef852d85-a11c-4b4f-81a1-e315998ef415.png)

Why? Why having a pivot of 0.2121 would make 0.18 unchanged? Why can't I just write 0.18 and have 0.18 unchanged? Is this a bug?

Here is the debug config:
[config.ocio.txt](https://github.com/AcademySoftwareFoundation/OpenColorIO/files/9032239/config.ocio.txt)

Remove the .txt at the end of the file name, did this because GitHub doesn't support uploading .ocio files.
