### ISSUE TITLE
v2.X.X Regression/bug with cccid handling in FileTransforms

### ISSUE THREAD

**Issue by KevinJW** [AcademySoftwareFoundation/OpenColorIO#1854]
Investigating a change in behaviour seen when trying to migrate a config from v1 to v2 being unable to load a ColorCorrection file, generating the error message when running `ociocheck`:

```
The transform file: test_config/master.cdl failed while building ops with this error: You must specify a valid cccid to load from the ccc file (either by name or index). id='' is not found in the file, and is not parsable as an integer index.
```
Points of note:
- The FileTransform is decoding the file as a CDL/CCC not a CC file due to the filename
- Renaming the file to .cc  and updating the config file - works as expected
- Our documentation states that passing a cccid as NULL or empty string should use the first CC found in the file
- Adding a cccid=0 to the FileTransform YAML works

Expected:

Based on historical behaviour in v1 we should continue to try decode the file based on the contents of the file and not the file extension. we should also follow the v2 documentation accepting the file as master.cdl and default to using the first (only) colour correction found in the file, without needing users to add an explicit cccid to the config.

This should work for files named .ccc as well as .cdl

As a thought experiment I'm unclear if this should be considered as several bugs:

1. Should the FileTransform continue to try load the file as a CC file after failing as a CDL/CCC?
2. Is the empty string bug found in both FileFormatCCC.cpp and FileFormat.CDL.cpp

Reproduction files...

minimal.ocio:
```
ocio_profile_version: 1
description: Minimal
search_path: .

roles:
  default: basic
  scene_linear: basic
  data: basic
  reference: basic
  compositing_log: basic
  color_timing: basic
  color_picking: basic
  texture_paint: basic
  matte_paint: basic
  rendering: basic
  aces_interchange: basic
  cie_xyz_d65_interchange: basic

displays:
  display:
    - !<View> {name: basic, colorspace: basic }
    - !<View> {name: cdl, colorspace: basic_cdl }

colorspaces:
  - !<ColorSpace>
    name: basic

  - !<ColorSpace>
    name: basic_cdl
    from_reference: !<FileTransform> { src: master.cdl }
```

master.cdl:
```
<?xml version="1.0" encoding="UTF-8"?>
<ColorCorrection>
   <SOPNode>
      <Description>No Op CDL</Description>
      <Slope>1.00000 1.00000 1.00000</Slope>
      <Offset>0.00000 0.00000 0.00000</Offset>
      <Power>1.00000 1.00000 1.00000</Power>
   </SOPNode>
   <SatNode>
      <Saturation>1.00000</Saturation>
   </SatNode>
</ColorCorrection>
```
