### ISSUE TITLE
ociocheck to spot duplicate Views

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#295]
Duplicate displays and views should probably cause a warning, in same way duplicate colorspaces do

E.g:

``` yaml
displays:
  sRGB:
    - !<View> {name: Film, colorspace: srgb8}
    - !<View> {name: Film, colorspace: srgb8}
    - !<View> {name: Log, colorspace: lg10}
    - !<View> {name: Raw, colorspace: nc10}
```
