### ISSUE TITLE
Config "description:" key for looks

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#344]
Minor thing: would be nice if looks could contain a `description:` key without raising a warning, e.g:

``` yaml
looks:
  - !<Look>
    name: example
    process_space: log
    transform: !<FileTransform> {src: "example.cc"}
    description: |
      Does such and such
```

Currently causes:

```
Unknown key in Look: 'description'. (line 40, column 4)
```
