### ISSUE TITLE
Resolve context vars in colorspace-references

### ISSUE THREAD

**Issue by dbr** [AcademySoftwareFoundation/OpenColorIO#364]
From the ocio-dev thread "Using environment variables/context to point to a colorspace"  by Donat Van Bellinghen,

> we frequently get footage shot with different cameras. I'd like to find a system to avoid having to tell the artist which camera has been used for which shot. I'd like to define a 'CameraRaw' colorspace that would point to other colorspaces in function of a context. So for example I would define it like this :

``` yaml
- !<ColorSpace>
    name: CameraRaw
    family: ""
    equalitygroup: ""
    bitdepth: 32f
    description: |
      Camera Raw depends on context
    isdata: false
    allocation: uniform
    allocationvars: [-0.125, 1.125]
    from_reference: !<ColorSpaceTransform> {src: linear, dst: $CAMERARAW}
```

> When I do this get an error from Nuke's viewer. OCIOColorSpace1: BuildColorSpaceOps failded, null dstColorSpace.

Regardless of that specific workflow, there's no immediately obvious reason why this wouldn't work. At the very least, it should fail with a nicer error message
