### ISSUE TITLE
[v1.1.1] Default display is alphabetical first if active_displays is not set

### ISSUE THREAD

**Issue by fnRaihanKibria** [AcademySoftwareFoundation/OpenColorIO#791]
According to https://opencolorio.org/userguide/config_syntax.html : "Unless the active_displays and active_views sections are defined, the first display and first view will be the default."

However using a config without an active_displays and active_views section results in the alphabetical first display being the default. Iterating through the displays also lists them in alphabetical order rather than the order of definition in the config file, although I'm not sure if that's intentional or not.

The views on the other hand are ordered correctly as they are in the config and default to the first in that order.

Config file snippet:
```
displays:
  zz:
    - !<View> {name: z1, colorspace: raw}
    - !<View> {name: y1, colorspace: Gamma2.4}
    - !<View> {name: x1, colorspace: rec709}
    - !<View> {name: a1, colorspace: sRGB}
  yy:
    - !<View> {name: z2, colorspace: raw}
    - !<View> {name: y2, colorspace: Gamma2.4}
    - !<View> {name: x2, colorspace: rec709}
    - !<View> {name: a2, colorspace: sRGB}
  xx:
    - !<View> {name: z3, colorspace: raw}
    - !<View> {name: y3, colorspace: Gamma2.4}
    - !<View> {name: x3, colorspace: rec709}
    - !<View> {name: a3, colorspace: sRGB}
  aa:
    - !<View> {name: z4, colorspace: raw}
    - !<View> {name: y4, colorspace: Gamma2.4}
    - !<View> {name: x4, colorspace: rec709}
    - !<View> {name: a4, colorspace: sRGB}
```

Test program:
```
#include <iostream>
#include <OpenColorIO/OpenColorIO.h>

namespace OCIO = OCIO_NAMESPACE;

int main()
{
    std::cout << "Using OCIO Version : " << OCIO_VERSION << std::endl;
    try
    {
        OCIO::ConstConfigRcPtr config = OCIO::GetCurrentConfig();
        std::cout << "default display: " << config->getDefaultDisplay() << std::endl;

        const int num_disps = config->getNumDisplays();
        std::cout << "number of displays: " << num_disps << std::endl;

        for(int i=0; i < num_disps; ++i) {
            const char* display = config->getDisplay(i);
            std::cout << "display " << i << " default view: " << config->getDefaultView(display) << std::endl;
            
            const int num_views = config->getNumViews(display);
            for(int k=0; k < num_views; ++k) {
                const char* view = config->getView(display, k);
                std::cout << "display " << i << ": " << display << " view " << k << ": " << view << std::endl;
            }
        }

    }
    catch(OCIO::Exception & exception)
    {
        std::cerr << "OpenColorIO Error: " << exception.what() << std::endl;
    }
}
```

Output:
```
Using OCIO Version : 1.1.1
default display: aa                // THIS SHOULD BE "zz"
number of displays: 4
display 0 default view: z4
display 0: aa view 0: z4
display 0: aa view 1: y4
display 0: aa view 2: x4
display 0: aa view 3: a4
display 1 default view: z3
display 1: xx view 0: z3
display 1: xx view 1: y3
display 1: xx view 2: x3
display 1: xx view 3: a3
display 2 default view: z2
display 2: yy view 0: z2
display 2: yy view 1: y2
display 2: yy view 2: x2
display 2: yy view 3: a2
display 3 default view: z1
display 3: zz view 0: z1
display 3: zz view 1: y1
display 3: zz view 2: x1
display 3: zz view 3: a1
```
