### ISSUE TITLE
Check if colorspace is invertible

### ISSUE THREAD

**Issue by vvzen** [AcademySoftwareFoundation/OpenColorIO#928]
Hi,

I'm currently writing an API on top of OCIO and I was wondering if there's a programmatic way to detect if a colorspace is not invertible. This could be helpful to automatically detect when we should avoid applying a colorspace transformation (since we don't use looks, some of our colorspaces also apply cdl/luts to give the final graded look, so being able to filter out non invertible colorspaces is a quite useful feature).

My current understanding is that if in the `FileTransform` of a Colorspace we have a 1D LUT, then  the transformation is always invertible (it's a 1 to 1 mapping) but if we have a 3D LUT (a potential many to 1 mapping), then the transformation is not invertible unless we have another 3D LUT that goes in the other direction. And that's one first thing to keep in mind when checking for invertibility. 

So I thought about checking the `from_reference` and `to_reference` directions of each colorspaces, if we have both on a colorspace definition, then it means we have all the informations on how to go to it and come back, which in my mind means it's invertible.

But if we take for example this colorspace:
```
- !<ColorSpace>
    name: Input - ARRI - V3 LogC (EI320) - Wide Gamut
    family: Input/ARRI
    equalitygroup: ""
    bitdepth: 32f
    description: |
      V3 LogC (EI320) - Wide Gamut

      ACES Transform ID : IDT.ARRI.Alexa-v3-logC-EI320.a1.v1
    isdata: false
    allocation: uniform
    allocationvars: [0, 1]
    to_reference: !<GroupTransform>
      children:
        - !<FileTransform> {src: V3_LogC_320_to_linear.spi1d, interpolation: linear}
        - !<MatrixTransform> {matrix: [0.680206, 0.236137, 0.083658, 0, 0.085415, 1.01747, -0.102886, 0, 0.002057, -0.062563, 1.06051, 0, 0, 0, 0, 1]}
``` 

it has got only a 1D Lut and a MatrixTransform. So I guess that if the matrix is invertible than the colorspace itself is actually invertible, even if it doesn't have a `from_reference` slot.

Am I wrong?
Does OCIO offer any kind of way to check for invertibility?

Thanks,

Valerio
